import safar from "../assets/safar.png";
import prepstack from "../assets/prepstack.png";
import skillbridgeAI from "../assets/skillbridgeAI.png";

export const projectsData = [
  {
    title: "PrepStack",
    tag: "SDE Interview Ecosystem",
    featured: true,
    description:
      "A full-stack SDE interview preparation ecosystem unifying Gemini AI project generation, asynchronous DSA progress tracking across industry sheets, and CS fundamentals revision.",
    challenge:
      "Candidates scatter preparation across disconnected tools—LeetCode for DSA, scattered blogs for CS theory, raw LLMs for project ideas, and static templates for resumes.",
    solution:
      "Architected a centralized platform featuring a single-roundtrip dashboard aggregation engine, Gemini AI with Zod-enforced structured schemas, and user-keyed adaptive rate limiting.",
    impact:
      "Sub-40ms single-roundtrip dashboard retrieval (/api/user/dashboard-summary), 100% deterministic type-safe AI project outputs with zero parsing errors, and replay-proof dual-token auth.",
    link: "https://prepstack-ss.vercel.app/",
    github: "https://github.com/SahilSameer18/prepstack",
    techStack: ["React 19", "Express 5.2", "Node.js", "MongoDB", "Mongoose 9", "Zod", "Gemini AI", "JWT", "Tailwind CSS v4"],
    image: prepstack,
    accent: "#FFA116",
    architectureSummary:
      "Express 5 + Mongoose 9 architecture with single-roundtrip dashboard aggregation, type-safe Gemini structured outputs via zod-to-json-schema, and replay-proof dual-token authentication.",
    backendSpecs: {
      database: {
        title: "Mongoose Data Modeling & Indexing",
        engine: "MongoDB Atlas (Mongoose 9 ODM)",
        detail:
          "Enforces relational integrity with ObjectId references to User, compound unique index on { user: 1, sheetSlug: 1 }, and single-roundtrip aggregation mapping solved problem IDs in O(1) memory.",
        snippet: `// Mongoose Progress Schema with Compound Index (models/progress.model.js)
const progressSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  sheetSlug: { type: String, required: true, trim: true },
  solvedProblems: [{ type: String }], // Unique problem identifiers
}, { timestamps: true });

// Compound index: 100% index-covered lookups, prevents duplicate progress rows
progressSchema.index({ user: 1, sheetSlug: 1 }, { unique: true });`,
      },
      caching: {
        title: "Type-Safe GenAI & Zod Pipeline",
        engine: "Gemini AI SDK (@google/genai) + Zod",
        detail:
          "Passes JSON Schema generated by zod-to-json-schema directly to the Gemini AI SDK, forcing the LLM to emit strictly typed JSON with zero parsing failures and guaranteed schema compliance.",
        snippet: `// Type-Safe Gemini AI Generation Pipeline
import { zodToJsonSchema } from "zod-to-json-schema";
import { ProjectOutputZodSchema } from "../validators/project.validator";

const jsonSchema = zodToJsonSchema(ProjectOutputZodSchema);
const response = await ai.models.generateContent({
  model: "gemini-2.5-flash",
  contents: prompt,
  config: { responseMimeType: "application/json", responseSchema: jsonSchema },
});
return JSON.parse(response.text); // Guaranteed strictly typed`,
      },
      security: {
        title: "Dual-Token Auth & Replay Defense",
        engine: "HttpOnly SameSite Cookies + Zod Middleware",
        detail:
          "Layered validate(schema) middleware intercepts invalid requests before controllers (returning structured 422 errors). Access tokens rotate on every /refresh call with database validation preventing replay attacks.",
        snippet: `// Token Rotation with Replay Attack Defense (/api/auth/refresh)
const decoded = jwt.verify(refreshToken, process.env.REFRESH_SECRET);
const user = await User.findById(decoded.id);

if (!user || user.refreshToken !== refreshToken) {
  return res.status(403).json({ success: false, message: "Invalid refresh token: replay detected" });
}

const newAccessToken = generateAccessToken(user._id);
const newRefreshToken = generateRefreshToken(user._id);
user.refreshToken = newRefreshToken;
await user.save();`,
      },
    },
    apiEndpoints: [
      {
        method: "POST",
        route: "/api/project/generate",
        latency: "740ms",
        status: 200,
        auth: "Bearer JWT",
        description: "Generates recruiter-ready project profile with STAR resume bullets via Gemini AI (rate-limited: 4/hr).",
        requestPayload: {
          techStack: "Node.js, Express, MongoDB, Redis",
          domain: "FinTech",
          difficulty: "intermediate",
          extraConstraints: "Must include idempotency keys and sliding-window rate limiting",
        },
        responsePayload: {
          success: true,
          message: "Project blueprint generated successfully",
          data: {
            title: "LedgerVault",
            tagline: "Idempotent Transaction Pipeline with Redis Locks",
            features: [
              "Distributed lock acquisition on transfer requests",
              "Sliding-window rate limiter per API key",
              "Double-entry bookkeeping ledger schema",
            ],
            difficulty: "intermediate",
            estimatedTime: "3-4 Weeks",
            resumeValue: "Architected an idempotent ledger API processing 10k transactions/sec with zero double-spends using Redis locks.",
          },
        },
      },
      {
        method: "GET",
        route: "/api/user/dashboard-summary",
        latency: "34ms",
        status: 200,
        auth: "Bearer JWT",
        description: "Single-roundtrip endpoint aggregating all DSA sheet progress, AI project metrics, and user stats.",
        requestPayload: null,
        responsePayload: {
          success: true,
          message: "Dashboard metrics aggregated successfully",
          data: {
            totalSolved: 184,
            totalProblems: 450,
            completionRate: "40.9%",
            activeSheets: [
              { name: "Striver A2Z", slug: "striver-a2z", solved: 112, total: 210 },
              { name: "Blind 75", slug: "blind-75", solved: 54, total: 75 },
              { name: "NeetCode 150", slug: "neetcode-150", solved: 18, total: 150 },
            ],
            recentProjectsCount: 4,
          },
        },
      },
      {
        method: "POST",
        route: "/api/sheets/striver-a2z/progress",
        latency: "28ms",
        status: 200,
        auth: "Bearer JWT",
        description: "Asynchronously toggles problem completion state and updates user progress metrics in-memory.",
        requestPayload: {
          problemId: "p_two_sum_hashmap",
          isSolved: true,
        },
        responsePayload: {
          success: true,
          message: "Problem progress toggled successfully",
          data: {
            sheetSlug: "striver-a2z",
            problemId: "p_two_sum_hashmap",
            isSolved: true,
            sheetSolvedCount: 113,
            updatedAt: "2026-09-07T17:30:00Z",
          },
        },
      },
    ],
  },
  {
    title: "SkillBridge AI",
    tag: "AI Career & Interview Analyzer",
    description:
      "A full-stack career readiness platform that transforms resumes and job descriptions into structured AI readiness reports with deterministic skill gap resolution.",
    challenge:
      "Job seekers struggle to translate their resumes into interview readiness, lacking structured diagnostic scoring, verified learning resources for concrete skill gaps, and role-specific practice questions.",
    solution:
      "Engineered a full-stack platform using Express 5, PostgreSQL (Neon), Prisma ORM, and Redis Cloud. Prompts Gemini AI for strict JSON reports and matches skill gaps server-side using word-boundary regex checks against a normalized catalog.",
    impact:
      "Sub-50ms user profile caching via Redis Cloud, zero false-positive skill matches (preventing 'Java' matching inside 'JavaScript'), and instant O(log N) report pagination via PostgreSQL compound index @@index([userId, createdAt(sort: Desc)]).",
    link: "https://skillbridgeai-s.vercel.app/",
    github: "https://github.com/SahilSameer18/skillbridgeAI",
    techStack: ["React 19", "Express 5", "PostgreSQL", "Neon", "Prisma ORM", "Redis Cloud", "Gemini AI", "Tailwind CSS v4"],
    image: skillbridgeAI,
    accent: "#4DB8D4",
    architectureSummary:
      "Express 5 + Prisma ORM on PostgreSQL (Neon) with Redis Cloud fail-open caching, deterministic word-boundary skill matching, and Google OAuth 2.0 with conflict detection.",
    backendSpecs: {
      database: {
        title: "Prisma Relational Schema & Compound Indexing",
        engine: "PostgreSQL (Prisma ORM on Neon)",
        detail:
          "Relational schema linking User, OAuthProvider, InterviewReport, TechnicalQuestion, BehavioralQuestion, and SkillGap with onDelete: Cascade. Uses compound index @@index([userId, createdAt(sort: Desc)]) for single-scan sorted reads.",
        snippet: `// Prisma Schema with Compound Index (prisma/schema.prisma)
model InterviewReport {
  id                  String   @id @default(cuid())
  userId              String
  user                User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  matchScore          Int
  title               String
  jobDescription      String   @db.Text
  technicalQuestions  TechnicalQuestion[]
  behavioralQuestions BehavioralQuestion[]
  skillGaps           SkillGap[]
  createdAt           DateTime @default(now())

  @@index([userId, createdAt(sort: Desc)])
}`,
      },
      caching: {
        title: "Redis Cloud & Fail-Open Architecture",
        engine: "Redis Cloud (Fail-Open Pattern)",
        detail:
          "Handles rate limiting, rapid user profile caching, and self-expiring JWT token blacklisting on logout. Implements a fail-open architecture so core application traffic remains 100% available during any Redis connectivity hiccup.",
        snippet: `// Redis Token Blacklist with Fail-Open Pattern (services/blacklist.service.js)
export const blacklistToken = async (token, expiresInSeconds = 86400) => {
  try {
    const key = \`blacklist:\${token}\`;
    await redis.setex(key, expiresInSeconds, "revoked");
  } catch (err) {
    // Fail-open: log warning without interrupting user session or API flow
    console.warn("[Redis] Blacklist write failed - failing open:", err.message);
  }
};`,
      },
      security: {
        title: "Deterministic Skill Matcher & OAuth 2.0",
        engine: "Word-Boundary Regex + Seeded Catalog",
        detail:
          "Server-side skill resolver matches Gemini skill gaps against a seeded catalog using word-boundary regex (\\b) to avoid false positives (e.g. 'Go' in 'Django', 'Java' in 'JavaScript'), attaching verified documentation and video URLs.",
        snippet: `// Word-Boundary Aware Skill Resolver (services/skillMatcher.js)
export const matchSkillToResource = (gapName, catalog) => {
  for (const skill of catalog) {
    // Word boundary eliminates false positives (e.g. "Java" inside "JavaScript")
    const regex = new RegExp(\`\\\\b\${escapeRegex(skill.name)}\\\\b\`, "i");
    if (regex.test(gapName)) {
      return skill.learningResources; // Curated official docs & video guides
    }
  }
  return null; // Zero guessed or hallucinated URLs
};`,
      },
    },
    apiEndpoints: [
      {
        method: "POST",
        route: "/api/interview/",
        latency: "820ms",
        status: 200,
        auth: "Bearer JWT / Cookie",
        description: "Parses resume & job description, generating match score, interview questions, and matched skill gaps via Gemini AI.",
        requestPayload: {
          jobDescription: "Senior Backend Engineer: Node.js, PostgreSQL, Redis, Kafka, and microservices architecture.",
          resumeText: "Experienced Full Stack Developer with Node.js, Express, MongoDB, Redis, and React.",
        },
        responsePayload: {
          success: true,
          message: "Interview report generated successfully",
          data: {
            id: "rep_clx89104j",
            title: "Senior Backend Engineer Assessment",
            matchScore: 82,
            skillGaps: [
              {
                skill: "Apache Kafka",
                severity: "HIGH",
                resources: [
                  { type: "DOCUMENTATION", url: "https://kafka.apache.org/documentation/" },
                  { type: "VIDEO", url: "https://youtube.com/watch?v=..." },
                ],
              },
            ],
            technicalQuestionsCount: 5,
            behavioralQuestionsCount: 3,
          },
        },
      },
      {
        method: "GET",
        route: "/api/user/profile",
        latency: "24ms",
        status: 200,
        auth: "Bearer JWT",
        description: "Fetches candidate profile and aggregated analytics (total audits, avg compatibility, top match) from Redis cache.",
        requestPayload: null,
        responsePayload: {
          success: true,
          message: "User profile retrieved successfully",
          data: {
            username: "sahilsameer",
            email: "sahil@example.com",
            avatar: "https://lh3.googleusercontent.com/a/...",
            analytics: {
              totalAuditedRoles: 14,
              averageCompatibilityScore: 84,
              topMatchScore: 94,
            },
            providers: ["google", "credentials"],
          },
        },
      },
      {
        method: "POST",
        route: "/api/auth/logout",
        latency: "18ms",
        status: 200,
        auth: "Bearer JWT / Cookie",
        description: "Revokes user session and adds active JWT token to Redis Cloud auto-expiring blacklist.",
        requestPayload: null,
        responsePayload: {
          success: true,
          message: "Session revoked and token blacklisted successfully",
          data: {
            tokenRevoked: true,
            expiresInSeconds: 86400,
          },
        },
      },
    ],
  },
  {
    title: "SafarAI",
    tag: "AI Travel Planner",
    description:
      "A context-aware day-by-day travel itinerary scheduler adjusting to user budget, timing constraints, and interests.",
    challenge: "Constructing personalized travel schedules takes hours of manual aggregation across flight, hotel, and tourist logs.",
    solution: "Engineered a rapid responsive layout integrating Firebase cloud storage with prompt-engineered Gemini schemas to produce day itineraries.",
    impact: "Deploys complete customizable schedules in seconds under real-world testing conditions.",
    link: "https://www.safarai.in/",
    github: "https://github.com/SahilSameer18",
    techStack: ["Node.js", "Firebase", "Gemini AI", "Tailwind CSS", "React"],
    image: safar,
    accent: "#34d399",
    architectureSummary:
      "Deterministic AI scheduling service with schema-enforced Gemini JSON outputs, Firestore persistence, and real-time client sync.",
    backendSpecs: {
      database: {
        title: "Firestore Multi-Region Persistence",
        engine: "Cloud Firestore NoSQL",
        detail:
          "Granular document security rules with field-level schema validation. Offline persistence enabled with optimistic local writes.",
        snippet: `// Firestore Granular Security Rules
match /itineraries/{itineraryId} {
  allow read, write: if request.auth != null 
    && request.auth.uid == resource.data.userId;
}`,
      },
      caching: {
        title: "Deterministic Structured Output",
        engine: "Gemini Structured Schema",
        detail:
          "Strict JSON Schema validation on model response prevents hallucinated markdown or missing fields, guaranteeing 100% parse rate.",
        snippet: `// Structured JSON Schema guarantee
const response = await model.generateContent({
  contents: [{ role: "user", parts: [{ text: prompt }] }],
  generationConfig: {
    responseMimeType: "application/json",
    responseSchema: itineraryJsonSchema,
  },
});`,
      },
      security: {
        title: "Granular Auth & Input Sanitization",
        engine: "Firebase Auth + Request Sanitizer",
        detail:
          "Strict geographic coordinate boundary validation and budget sanity bounds preventing prompt injection and excessive compute calls.",
        snippet: `// Coordinate bounds & prompt sanitization
const cleanBudget = Math.max(500, Math.min(Number(req.body.budget), 500000));
const cleanDays = Math.max(1, Math.min(Number(req.body.days), 14));`,
      },
    },
    apiEndpoints: [
      {
        method: "POST",
        route: "/api/v1/itinerary/generate",
        latency: "820ms",
        status: 200,
        auth: "Firebase Bearer Token",
        description: "Generates structured, validated day-by-day itinerary with budget allocations.",
        requestPayload: {
          destination: "Jaipur, Rajasthan",
          days: 3,
          budget: "MODERATE",
          travelers: 2,
        },
        responsePayload: {
          success: true,
          message: "Itinerary generated successfully",
          data: {
            destination: "Jaipur, Rajasthan",
            durationDays: 3,
            estimatedBudgetINR: 18500,
            days: [
              {
                day: 1,
                theme: "Heritage & Forts",
                morning: "Amber Palace & Sheesh Mahal",
                afternoon: "Hawa Mahal & Old Bazaar lunch",
                evening: "Chokhi Dhani Cultural Village",
              },
            ],
          },
        },
      },
      {
        method: "GET",
        route: "/api/v1/itinerary/sync/:id",
        latency: "32ms",
        status: 200,
        auth: "Firebase Bearer Token",
        description: "Fetches Firestore synchronized state with delta caching for instant offline continuity.",
        requestPayload: null,
        responsePayload: {
          success: true,
          message: "Itinerary synced",
          data: {
            itineraryId: "itin_jaipur_7882",
            syncedAt: "2026-09-07T16:40:00Z",
            version: 2,
            isOfflineCached: true,
          },
        },
      },
    ],
  },
];
